**MAESTRÍA EN INTELIGENCIA ARTIFICIAL APLICADA**

**Curso: TC5053 - Ciencia y analítica de datos**

Tecnológico de Monterrey

Prof Grettel Barceló Alonso

**Semana 3**
Bases, almacenes y manipulación de datos

---

*   NOMBRE: Fernando Gomez Moreno
*   MATRÍCULA: A00354097

---

En esta actividad usarás una base de datos relacional basada en el informe de participación y la lista del top 10 de Netflix. Incluye películas y programas de televisión, así como información sobre temporadas, métricas de visualización, fechas de estreno, duración y más, organizada en las siguientes tablas:

* `movie`: Información general de las películas.

* `tv_show`: Información general de los programas de televisión.

* `season`: Datos de las temporadas asociadas a cada programa de TV.

* `view_summary`: Métricas de visualización y rendimiento de películas o temporadas.

Revisa con detalle su esquema para que comprendas cómo se relacionan las tablas anteriores.

**NOTA IMPORTANTE:** Asegúrate de responder *explícitamente* todos los cuestionamientos.

`PyMySQL` es una librería escrita en Python puro que funciona como conector (*driver*) para motores de bases de datos MySQL, permitiendo abrir conexiones, ejecutar consultas SQL y recuperar resultados directamente desde programas en Python.

In [70]:
pip install pymysql

Requirement already satisfied: pymysql in /opt/anaconda3/lib/python3.13/site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

`SQLAlchemy` es una librería de Python que facilita la interacción con bases de datos y permite mantener un pool de conexiones eficiente, gestionar *commits* y *rollbacks* de forma automática y asegurar que múltiples conexiones simultáneas se manejen de manera segura, incluso cuando se ejecutan consultas SQL “puras”

In [71]:
# Importa las librerías necesarias
import pymysql
import sqlalchemy as sqla
import pandas as pd

Se crea una conexión (`conn`) para luego invocar declaraciones SQL.

In [72]:
# motor+driver://usuarioBD:clave@ipHostDBMS:puerto/esquema
# pool_recycle controla el tiempo máximo de vida de una conexión en el pool (3600 segundos = 1 hora)
db = sqla.create_engine('mysql+pymysql://mnaTC4029User:mnaTC4029Pass!@20.51.200.131:3306/Netflix', pool_recycle=3600)
conn = db.connect()

Para que tus consultas sean más legibles y fáciles de mantener, puedes usar este formato multilínea con comillas triples y `sqla.text()`. Por ejemplo:

```
query = sqla.text("""
  SELECT ---
  FROM ---
  WHERE ---
""")
pd.read_sql(query, conn)
```

1.	Extrae la información de las películas que duran más de 5 horas.

In [73]:
# La columna de runtime guarda el tiempo total en minutos de duración de una pelicula. 
# Por lo tanto 5 horas es equivanlente a 300 minutos.
query = sqla.text("""
  SELECT *
  FROM movie
  WHERE runtime > 300
""")
pd.read_sql(query, conn)

# Como resultado tenemos 5 peliculas que duran más de 5 horas.

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,5793,2024-01-01,2024-01-01,b'\x00',None,日本統一シリーズ: 映画シリーズ,None,3892,Nihontouitsu Series: Film Series
1,5794,2024-01-01,2024-01-01,b'\x00',None,釣りバカ日誌: 映画シリーズ,None,2120,Free and Easy Series: Film Series
2,5874,2024-01-01,2024-01-01,b'\x01',None,None,2021-08-06,312,Navarasa: Limited Series
3,9729,2024-01-01,2024-01-01,b'\x00',None,織田同志会 織田征仁: 映画シリーズ,None,710,Seiji Oda: Film Series
4,9730,2024-01-01,2024-01-01,b'\x00',None,キングダム～首領になった男～: 映画シリーズ,None,427,Kingdom ~ The Man Who Became the Top ~: Film S...

2.	¿Cuál es el porcentaje de películas disponibles únicamente en EU en relación con el total, excluyendo los valores `NULL`?

In [74]:
query = sqla.text("""
  SELECT SUM(CASE WHEN available_globally = TRUE THEN 1 ELSE 0 END) AS Peliculas_Disponibles_en_EU,
  COUNT(available_globally) AS Total_de_Peliculas_Not_Null,
  CAST(SUM(CASE WHEN available_globally = TRUE THEN 1 ELSE 0 END) AS DECIMAL(10, 2)) * 100 / COUNT(available_globally) AS Percentage_Available_US
  FROM movie
  WHERE available_globally is not NULL
""")
pd.read_sql(query, conn)

# 16.42% es el percentaje total de peliculas disponibles en EU.

,Peliculas_Disponibles_en_EU,Total_de_Peliculas_Not_Null,Percentage_Available_US
0,1826.0,11115,16.42825

3.	¿Cuáles son los idiomas o regiones originales en la tabla de películas?
* ¿Cuántas películas tienen el campo `locale` con valor `NULL`?

In [75]:
query = sqla.text("""
  SELECT DISTINCT(locale), count(*)
  FROM movie
  GROUP BY locale
""")
pd.read_sql(query, conn)

# Los idiomas o regiones en la table son "None" y "en"
# Peliculas que tiene campo locale con valor NULL son 11255 igual que None.

# Use un query solo para verificar los locale con valor NULL e igualmente una UNION ALL
#
#query = sqla.text("""
#  SELECT count(*)
#  FROM movie
#  WHERE locale IS NULL
# """)
# pd.read_sql(query, conn)
#
#
#query = sqla.text("""
#  SELECT locale, COUNT(*) AS total_peliculas
#  FROM movie
#  WHERE locale IS NOT NULL
#  GROUP BY locale
#  UNION ALL
#  SELECT 'Locale_NULLS' AS locale, COUNT(*) AS total_peliculas
#  FROM movie
#  WHERE locale IS NULL
#  ORDER BY total_peliculas DESC
# """)
# pd.read_sql(query, conn)
#

  locale  count(*)
0   None     11255
1     en       532

4.	Asumiendo que los valores `NULL` en `locale` corresponden a otro idioma (diferente del inglés), el título original de la película NO debería coincidir con el título principal en dichos registros.
* Determina cuántas películas tienen títulos diferentes en estos dos campos (`title` y `original_title`).
*  ¿Coinciden los resultados (cantidad de `NULL` y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes.
* Finalmente, concluye si la suposición de que los valores `NULL` en `locale` indican que la película está en otro idioma es válida.

4. El titulo original se refiere al titulo de la region o locale por lo tanto no deberia coincidir con el titulo principal, ya que el titulo principal es en inglés.

In [76]:
query = sqla.text("""
  SELECT COUNT(*)
  FROM movie
  WHERE original_title <> title
""")
pd.read_sql(query, conn)

# 3947 peliculas tienen diferencia en titulo y titulo original

# ¿Coinciden los resultados (cantidad de `NULL` y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes.
# No coinciden porque no se esta tomando en cuenta la diferencia con None y NULL. Solo se toma en cuenta los valores de texto en original_title.
# Conclusión: Si los valores en locale es NULL entonces la pelicula está en otro idioma independientemente is esta en EU o no.

   COUNT(*)
0      3947

5.	Determina el título de la película que ha permanecido más tiempo en el top 10.

In [77]:
query = sqla.text("""
  SELECT m.title, v.cumulative_weeks_in_top10
  FROM movie m
  JOIN view_summary v ON m.id = v.movie_id
  ORDER BY
  v.cumulative_weeks_in_top10 DESC
  LIMIT 1
""")
pd.read_sql(query, conn)

# La pelicula "The Boss Baby" permanecio 22 semanas en top 10.

           title  cumulative_weeks_in_top10
0  The Boss Baby                         22

6.	Identifica los 10 programas de TV con mayor cantidad de temporadas.

In [78]:
query = sqla.text("""
  SELECT tvs.title, s.season_number
  FROM tv_show tvs
  JOIN season s ON tvs.id = s.tv_show_id
  WHERE s.season_number > 10
  ORDER BY
  s.season_number DESC
  LIMIT 10
""")
pd.read_sql(query, conn)

# Top 10 de programas de TV con mayor cantidad de temporadas.

                                               title  season_number
0                         How do you like Wednesday?       23701998
1                         How do you like Wednesday?       21212020
2        Gen Hoshino Concert Recollections 2015-2023       20152023
3                         How do you like Wednesday?       18002002
4                                          ONE PIECE        8921000
5  How do you like Wednesday?: Entry into the Arc...        6201998
6                                          ONE PIECE         406407
7                         How do you like Wednesday?         211997
8       How do you like Wednesday?: Mission complete         202007
9                         How do you like Wednesday?          61999

7.	¿Cuáles son los intervalos de fechas de los resúmenes en la tabla `view_summary` de los períodos (`duration`) semestrales?

In [79]:
query = sqla.text("""
  SELECT start_date, end_date, duration
  FROM view_summary
  WHERE duration = 'SEMI_ANNUALLY'
  ORDER BY start_date
""")
pd.read_sql(query, conn)

# Solo estan Semanalmente y Semi anual cada seis meses

## Tambine se puede identificar por el numero de dias por semestre que varia de 180 a 184
#query = sqla.text("""
#  SELECT start_date, end_date, DATEDIFF(end_date, start_date) AS duracion_dias
#  FROM view_summary
#  WHERE DATEDIFF(end_date, start_date) BETWEEN 180 AND 184
#  ORDER BY start_date
#""")
#pd.read_sql(query, conn)

# 31794 records.

       start_date    end_date       duration
0      2023-07-01  2023-12-31  SEMI_ANNUALLY
1      2023-07-01  2023-12-31  SEMI_ANNUALLY
2      2023-07-01  2023-12-31  SEMI_ANNUALLY
3      2023-07-01  2023-12-31  SEMI_ANNUALLY
4      2023-07-01  2023-12-31  SEMI_ANNUALLY
...           ...         ...            ...
31789  2024-01-01  2024-06-30  SEMI_ANNUALLY
31790  2024-01-01  2024-06-30  SEMI_ANNUALLY
31791  2024-01-01  2024-06-30  SEMI_ANNUALLY
31792  2024-01-01  2024-06-30  SEMI_ANNUALLY
31793  2024-01-01  2024-06-30  SEMI_ANNUALLY

[31794 rows x 3 columns]

8.	Ordena las temporadas de *Grey's Anatomy* según la cantidad de vistas registradas en el primer período semestral de 2024.
* ¿Cómo interpretarías los resultados obtenidos?

In [80]:
query = sqla.text("""
  SELECT s.title, s.tv_show_id, vs.views
  FROM season s
  JOIN view_summary vs ON s.id = vs.season_id 
  WHERE s.title like 'Grey%' AND vs.start_date >= '2024-01-01' AND vs.end_date <= '2024-06-30'
  ORDER BY vs.views DESC
""")
pd.read_sql(query, conn)

# Intepreto los resultados que cuando se estreno la temporada de Grey's Anatomy fue cuando tuve mas audiencia
# después fue bajando la audiencia en cuanto salìan mas temporadas.

                        title  tv_show_id    views
0    Grey's Anatomy: Season 1         347  3600000
1    Grey's Anatomy: Season 2         347  3100000
2    Grey's Anatomy: Season 5         347  2900000
3    Grey's Anatomy: Season 4         347  2900000
4    Grey's Anatomy: Season 3         347  2900000
5    Grey's Anatomy: Season 6         347  2800000
6    Grey's Anatomy: Season 7         347  2700000
7    Grey's Anatomy: Season 8         347  2600000
8    Grey's Anatomy: Season 9         347  2500000
9   Grey's Anatomy: Season 10         347  2400000
10  Grey's Anatomy: Season 11         347  2200000
11  Grey's Anatomy: Season 19         347  2000000
12  Grey's Anatomy: Season 14         347  2000000
13  Grey's Anatomy: Season 13         347  2000000
14  Grey's Anatomy: Season 12         347  2000000
15  Grey's Anatomy: Season 15         347  1900000
16  Grey's Anatomy: Season 16         347  1800000
17  Grey's Anatomy: Season 18         347  1700000
18  Grey's Anatomy: Season 17         347  1700000
19  Grey's Anatomy: Season 20         347   100000

9.	Todas las consultas anteriores podrían hacerse también con la lógica relacional implementada en Pandas, que permite replicar la mayoría de las operaciones de SQL. Si los dataframes se han llenado como sigue, resuelve la consulta 8 utilizando las funciones de Pandas.

In [81]:
tv_show = pd.read_sql(sqla.text('SELECT * FROM tv_show'), conn)
season = pd.read_sql(sqla.text('SELECT * FROM season'), conn)
view_summary = pd.read_sql(sqla.text('SELECT * FROM view_summary'), conn)

In [82]:
df_combinado = pd.merge(
    season,
    view_summary,
    left_on='id',
    right_on='season_id',
    how='inner'
)
df_filtrado = df_combinado.query(
    "title.str.startswith('Grey', na=False) and "
    "@pd.to_datetime(start_date) >= @pd.to_datetime('2024-01-01') and "
    "@pd.to_datetime(end_date) <= @pd.to_datetime('2024-06-30')"
)
df_resultado = df_filtrado.sort_values(
    by='views',
    ascending=False
)[['title', 'tv_show_id', 'views']]
print(df_resultado.head())

                         title  tv_show_id    views
986   Grey's Anatomy: Season 1         347  3600000
1188  Grey's Anatomy: Season 2         347  3100000
1288  Grey's Anatomy: Season 3         347  2900000
1290  Grey's Anatomy: Season 5         347  2900000
1301  Grey's Anatomy: Season 4         347  2900000

`MySQL` es un sistema de gestión de bases de datos relacional, pero desde Python también es posible extraer información de bases de datos no relacionales, como `Firestore`, `MongoDB` o `Cassandra`, utilizando conectores o integraciones específicas. Esto permite combinar datos de diferentes fuentes según las necesidades del análisis o la aplicación.

En el siguiente ejercicio usarás un ejemplo con `Firestore` desde Python. Para ello utilizarás los módulos `credentials` y `firestore` de la biblioteca `firebase_admin`.

In [83]:
!pip install firebase_admin
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

Requirement already satisfied: firebase_admin in /opt/anaconda3/lib/python3.13/site-packages (7.1.0)
Requirement already satisfied: cachecontrol>=0.14.3 in /opt/anaconda3/lib/python3.13/site-packages (from firebase_admin) (0.14.3)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.25.1 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (2.25.1)
Requirement already satisfied: google-cloud-firestore>=2.21.0 in /opt/anaconda3/lib/python3.13/site-packages (from firebase_admin) (2.21.0)
Requirement already satisfied: google-cloud-storage>=3.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from firebase_admin) (3.4.0)
Requirement already satisfied: pyjwt>=2.10.1 in /opt/anaconda3/lib/python3.13/site-packages (from pyjwt[crypto]>=2.10.1->firebase_admin) (2.10.1)
Requirement already satisfied: httpx==0.28.1 in /opt/anaconda3/lib/python3.13/site-packages (from httpx[http2]==0.28.1->firebase_admin) (0.28.1)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.13/site-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (4.7.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (2025.8.3)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.13/site-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (3.7)
Requirement already satisfied: h2<5,>=3 in /opt/anaconda3/lib/python3.13/site-packages (from httpx[http2]==0.28.1->firebase_admin) (4.3.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (1.70.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (6.32.1)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (1.26.1)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (2.40.3)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (2.32.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (1.75.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (1.75.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (5.5.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (4.9.1)
Requirement already satisfied: typing-extensions~=4.12 in /opt/anaconda3/lib/python3.13/site-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (4.12.2)
Requirement already satisfied: hyperframe<7,>=6.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase_admin) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase_admin) (4.1.0)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (0.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (2.3.0)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/anaconda3/lib/python3.13/site-packages (from rsa<5,>=3.1.4->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=2.25.1->google-api-core[grpc]<3.0.0dev,>=2.25.1; platform_python_implementation != "PyPy"->firebase_admin) (0.4.8)
Requirement already satisfied: msgpack<2.0.0,>=0.5.2 in /opt/anaconda3/lib/python3.13/site-packages (from cachecontrol>=0.14.3->firebase_admin) (1.0.3)
Requirement already satisfied: google-cloud-core<3.0.0,>=1.4.1 in /opt/anaconda3/lib/python3.13/site-packages (from google-cloud-firestore>=2.21.0->firebase_admin) (2.4.3)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.7.2 in /opt/anaconda3/lib/python3.13/site-packages (from google-cloud-storage>=3.1.1->firebase_admin) (2.7.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.1.3 in /opt/anaconda3/lib/python3.13/site-packages (from google-cloud-storage>=3.1.1->firebase_admin) (1.7.1)
Requirement already satisfied: cryptography>=3.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from pyjwt[crypto]>=2.10.1->firebase_admin) (44.0.1)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->firebase_admin) (1.17.1)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->firebase_admin) (2.21)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.13/site-packages (from anyio->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (1.3.0)

En `Firestore`, a diferencia de `MySQL` donde se utiliza un usuario y contraseña para conectarse, la autenticación se realiza mediante un archivo JSON que almacena las credenciales necesarias para acceder a la base de datos. Este archivo contiene las claves y la información de configuración que permiten a Python establecer la conexión de manera segura.

In [84]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

In [ ]:
# Debes descargar el archivo de credenciales "consultancy.json" (disponible en las instrucciones de Canvas) y ubicarte en la carpeta donde lo almacenaste
import os
DIR = "/Users/chicano/Documents/Tec/1-Trimestre/Ciencia y Analisis de datos/Semana 3 - (Sep 22-29)"
os.chdir(DIR)

In [ ]:
# consultancy.json almacena la clave privada para autenticar una cuenta y autorizar el acceso a los servicios
# A través de la función Certificate(), se regresa una credencial inicializada, que puedes utilizar para crear una nueva instancia de la aplicación
cred = credentials.Certificate('consultancy.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

10.	Investiga cómo leer la colección `EMPLOYEE` y mostrar su contenido en un dataframe. Asegúrate de incluir el `id` en el resultado

In [ ]:
employee_collection = db.collection('EMPLOYEE')
docs = empleados_ref.stream()
datos_empleados = []
for doc in docs:
    registro = doc.to_dict()
    registro['id'] = doc.id 
    datos_empleados.append(registro)

print(f"Documentos leídos: {len(datos_empleados)}")

In [ ]:
firebase_admin.delete_app(firebase_admin.get_app())